/*------[Product Categories]------
	men top
	men bottom
	men outerwear
	women top
	women bottom
	women dress
	women skirt
*/

/*------[JSON format]------
	{name: "", image: ``, bonusImages: [``, ``, ``, ``, ``], price: "", description: "", features: ""},
*/


const categoryNames = [
	"Men Top",
	"Men Bottom",
	"Men Outerwear",
	"Women Top",
	"Women Bottom",
	"Women Dress",
	"Women Skirt"
];


//men top
menTopPath = "../../img/men-top/";
menTopIDHead = "men-top-";
menTopExtn = ".webp"
const menTop = [
	{name: "Yellow Zippered Pocket T-Shirt", image: `${menTopPath}${menTopIDHead}1${menTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "59.99", description: "This adult apparel top is constructed with a spacious relaxed silhouette and engineered from a lightweight knit cotton blend fabric that optimizes airflow during warm-weather wear. The design features a flexible crew neck paired with comfortable short sleeves to ensure an easygoing and unrestrictive fit. Practical storage is provided by a high-contrast dark olive chest pocket featuring a full vertical zipper track for secure small-item storage. Ideal for casual outdoor activities, summer travel, or relaxed weekend lounging, this top provides objective utility and easy coordination with matching cargo shorts or athletic wear.", features: "Casual Short-Sleeve Tee | Crew Neckline | Contrast Olive Chest Pocket | Vertical Zipper Closure | Smooth Knit Fabric | Relaxed Fit | Cargo Bottoms Styling Compatibility"},
	{name: "White Zipped Pocket Knit T-Shirt", image: `${menTopPath}${menTopIDHead}2${menTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "69.99", description: "This adult apparel top is constructed with a relaxed silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during daily casual wear. The design features a structured crew collar paired with roomy drop-shoulder sleeves to ensure comfortable movement and an unrestrictive fit. Practical storage is provided by a contrasting synthetic chest pocket equipped with a vertical zipper closure, adding an urban functional visual accent. Ideal for casual neighborhood walks, weekend outings, or relaxed everyday wear, this short-sleeve shirt provides objective utility and easy coordination with casual shorts or utility trousers.", features: "Short-Sleeve T-Shirt | Crew Neckline | Contrast Zippered Chest Pocket | Smooth Knit Texture | Drop-Shoulder Fit | Double-Stitched Bottom Hem | Utility Bottoms Styling Compatibility"},
	{name: "Abstract Graphic Crewneck T-Shirt", image: `${menTopPath}${menTopIDHead}3${menTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "59.99", description: "This adult apparel top is constructed with a classic relaxed silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during recreational activities. The design features a durable ribbed crew collar paired with standard short sleeves to ensure a reliable and flexible fit during casual movement. Focal visual interest is provided by a centered abstract dye-effect graphic print across the front torso, offering a modern artistic accent. Ideal for casual social gatherings, relaxed weekend lounging, or urban streetwear coordination, this graphic tee provides objective style and easy pairing with dark shorts or denim.", features: "Graphic Crewneck Tee | Ribbed Neck Collar | Abstract Front Print | Smooth Knit Texture | Standard Short Sleeves | Straight Bottom Hem | Casual Bottoms Styling Compatibility"},
	{name: "Gradient Dip-Dye Crewneck T-Shirt", image: `${menTopPath}${menTopIDHead}4${menTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "79.99", description: "This adult apparel top is constructed with a relaxed silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during recreational activities. The design features a durable crew neck collar paired with standard short sleeves to ensure a reliable and flexible fit during active movement. Visual emphasis is provided by a seamless two-tone dip-dye transition from deep navy to bright white, accented by subtle branding across the upper left chest. Ideal for casual neighborhood walks, weekend social gatherings, or relaxed coastal outings, this tee provides objective utility and easy coordination with neutral shorts or trousers.", features: "Dip-Dye Graphic | Crew Neckline | Smooth Knit Texture | Drop-Shoulder Silhouette | Chest Branding Detail | Double-Stitched Bottom Hem | Neutral Bottoms Styling Compatibility"},
	{name: "Solid Cream Heavyweight T-Shirt", image: `${menTopPath}${menTopIDHead}5${menTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "59.99", description: "This adult apparel top is constructed with a spacious relaxed silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during warm-weather wear. The design features a structured crew collar paired with extended short sleeves to ensure an unrestrictive and comfortable fit throughout daily activities. Minimalist aesthetics are prioritized with a clean monochrome finish, subtly detailed with a small woven brand tag near the lower hem. Ideal for casual indoor lounging, daily errands, or layered streetwear styling, this minimalist shirt provides objective utility and easy coordination with casual trousers or shorts.", features: "Solid Monochrome Top | Structured Crew Collar | Smooth Knit Texture | Extended Short Sleeves | Hem Accent Tag | Relaxed Boxy Fit | Casual Bottoms Styling Compatibility"},
	{name: "Full-Zip Utility Short-Sleeve Shirt", image: `${menTopPath}${menTopIDHead}6${menTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "99.99", description: "This adult apparel top is constructed with a boxy relaxed silhouette and engineered from a lightweight woven fabric that optimizes structure and durability during everyday wear. The design features a smart point collar paired with a full-length central zipper closure to ensure versatile layering options and effortless wearability. Functional detail is integrated via subtle horizontal chest seams and discreet side pockets for convenient daily storage. Ideal for casual urban commuting, evening social outings, or light outer layering, this short-sleeve jacket provides objective utility and easy coordination with matching utility shorts or trousers.", features: "Full-Zipper Closure | Turn-Down Point Collar | Woven Lightweight Texture | Short-Sleeve Utility Cut | Functional Pocket Details | Boxy Silhouette | Matching Bottoms Styling Compatibility"},
	{name: "Open-Collar Textured Knit Polo", image: `${menTopPath}${menTopIDHead}7${menTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "89.99", description: "This adult apparel top is constructed with a relaxed silhouette and engineered from a textured knit cotton blend fabric that optimizes breathability and visual depth during casual activities. The design features a smart open notch collar paired with ribbed sleeve cuffs and a banded hem to ensure a clean, tailored drape across the torso. Subtle waffle-knit texture provides refined stylistic interest without sacrificing easygoing comfort. Ideal for smart-casual neighborhood walks, weekend cafe visits, or relaxed evening gatherings, this short-sleeve polo provides objective utility and easy coordination with tailored shorts or chinos.", features: "Open Notch Collar | Textured Waffle Knit | Ribbed Cuffs and Hem | Breathable Cotton Blend | Relaxed Fit | Smart-Casual Silhouette | Chino Bottoms Styling Compatibility"},
	{name: "Solid Black Heavyweight T-Shirt", image: `${menTopPath}${menTopIDHead}8${menTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "59.99", description: "This adult apparel top is constructed with a spacious relaxed silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during warm-weather wear. The design features a durable crew collar paired with roomy drop-shoulder short sleeves to ensure an unrestrictive and comfortable fit throughout daily movement. Clean monochrome styling offers maximum versatility, subtly accenting the lower hem with a small yellow woven brand tag. Ideal for casual indoor lounging, daily errands, or effortless streetwear coordination, this minimalist shirt provides objective utility and easy pairing with denim jeans or athletic shorts.", features: "Solid Black Finish | Crew Neckline | Smooth Heavyweight Knit | Drop-Shoulder Sleeves | Hem Accent Tag | Loose Relaxed Fit | Denim Bottoms Styling Compatibility"},
];



//men bottom
menBotPath = "../../img/men-bottom/";
menBotIDHead = "men-bot-";
menBotExtn = ".webp"
const menBottom = [
	{name: "Casual Black Shorts", image: `${menBotPath}${menBotIDHead}1${menBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "59.99", description: "These adult apparel bottoms are constructed with a relaxed silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during recreational activities. The design features a supportive elastic waistband paired with an adjustable external drawstring to ensure a reliable and customized fit during active movement. Practical storage is provided by discreet side pockets, while contrast vertical piping running down the sides offers a minimal visual accent. Ideal for casual neighborhood walks, indoor gym sessions, or relaxed weekend lounging, these shorts provide objective utility and easy coordination with casual t-shirts", features: "Casual Shorts | Drawstring and Elastic Closure | Side Piping Detail | Smooth Knit Texture | Functional Side Pockets | Double-Stitched Bottom Hem | T-Shirt Styling Compatibility"},
	{name: "Straight-Cut Denim Jeans", image: `${menBotPath}${menBotIDHead}2${menBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "89.99", description: "These adult apparel bottoms are constructed with a classic straight-leg silhouette and engineered from a durable woven cotton denim fabric that delivers structural integrity during daily activities. The design features a traditional waistband with structured belt loops paired with a secure zip-fly and button closure to ensure a reliable and tailored fit throughout wear. Practical storage is provided by classic 5-pocket styling, including deep front scoop pockets, a coin pocket, and clean back patch pockets for functional utility. Ideal for casual weekend outings, everyday urban commuting, or relaxed social gatherings, these denim trousers provide objective versatility and effortless coordination with modern casual tees and sneakers.", features: "Classic Denim Jeans | Zip-Fly and Button Closure | Traditional 5-Pocket Layout | Light Wash Cotton Fabric | Straight-Leg Cut | Reinforced Belt Loops | Daily Casual Styling Compatibility"},
	{name: "Beige Slim-Fit Stretch Trousers", image: `${menBotPath}${menBotIDHead}3${menBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "109.99", description: "These adult apparel bottoms are constructed with a refined slim-straight silhouette and engineered from a smooth woven stretch-blend fabric that optimizes mobility and shape retention. The design features a clean tailored waistband with integrated belt loops paired with a concealed fly closure to maintain a polished profile suitable for smart-casual environments. Practical storage is provided by functional slant side pockets and clean rear welt pockets, while crisp front leg creases offer a structured visual accent. Ideal for office workdays, formal dinners, or elevated casual weekend wear, these trousers provide objective utility and seamless styling compatibility with dress shirts, polo tops, or loafers.", features: "Tailored Smart Trousers | Concealed Fly and Button Closure | Easy-Care Stretch Fabric | Functional Slant Side Pockets | Pressed Center Crease | Belt Loop Waistband | Smart-Casual Styling Compatibility"},
	{name: "Oversized Wide-Leg Sweatpants", image: `${menBotPath}${menBotIDHead}4${menBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "79.99", description: "These adult apparel bottoms are constructed with a relaxed wide-leg silhouette and engineered from a heavy-knit fleece cotton blend that maximizes comfort during indoor and outdoor casual wear. The design features a broad supportive elastic waistband designed to rest comfortably at the hips without pinching during prolonged movement. Practical storage is provided by deep side-seam pockets with discreet zipper closures to keep small essentials secure, while subtle leg pleating offers an intentional streetwear drape. Ideal for relaxed lounge settings, outdoor travel, or casual athletic streetwear ensembles, these sweatpants offer objective utility and easy pairing with hoodies and lifestyle sneakers.", features: "Relaxed Sweatpants | Broad Elastic Waistband | Zippered Side Pockets | Heavyweight Knit Texture | Wide-Leg Relaxed Cut | Minimalist Monochromatic Finish | Streetwear and Lounge Styling Compatibility"},
	{name: "Slim-Fit Bleached Jeans", image: `${menBotPath}${menBotIDHead}5${menBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "89.99", description: "These adult apparel bottoms are constructed with a streamlined slim-fit silhouette and engineered from a flexible stretch-cotton denim fabric that optimizes comfort and freedom of movement throughout wear. The design features a supportive mid-rise waistband paired with a classic zip-fly and metallic button closure to ensure a secure and tailored fit. Practical storage is provided by classic 5-pocket styling, including deep front scoop pockets, a coin pocket, and reinforced back patch pockets. Ideal for casual day-outs, street-style wardrobe coordination, or relaxed weekend gatherings, these light-wash jeans provide objective utility and easy pairing with casual t-shirts and lifestyle sneakers.", features: "Slim-Fit Stretch Denim | Zip-Fly and Button Closure | Bleached Light Wash Finish | Classic 5-Pocket Layout | Flexible Cotton-Blend Fabric | Reinforced Belt Loops | Casual Streetwear Styling Compatibility"},
	{name: "Athletic Performance Mesh Shorts", image: `${menBotPath}${menBotIDHead}6${menBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "49.99", description: "These adult apparel bottoms are constructed with an above-the-knee athletic silhouette and engineered from a lightweight, quick-dry performance fabric that optimizes breathability during high-intensity training. The design features a broad elastic waistband paired with contrast black trim along the hem and side seams to offer a clean sport-inspired visual accent. Practical storage is provided by discreet side pockets designed to carry lightweight essentials without adding bulk during movement. Ideal for basketball sessions, outdoor running, gym workouts, or casual athletic wear, these performance shorts provide objective utility and seamless pairing with training tees or tank tops.", features: "Athletic Performance Shorts | Broad Elastic Waistband | Contrast Hem Trim Detail | Moisture-Wicking Dry Stretch Fabric | Functional Side Pockets | Lightweight Breathable Mesh | Activewear Styling Compatibility"},
	{name: "Tailored Ankle-Length Trousers", image: `${menBotPath}${menBotIDHead}7${menBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "109.99", description: "These adult apparel bottoms are constructed with a modern ankle-length straight-fit silhouette and engineered from a smooth woven cotton-blend fabric that maintains a crisp profile throughout wear. The design features a tailored waistband with sturdy belt loops paired with a clean front fly closure to ensure a sophisticated visual line. Practical storage is provided by functional side slant pockets and back welt pockets, while the slightly cropped hem offers a modern architectural finish. Ideal for professional office environments, formal events, or elevated evening dining, these trousers provide objective utility and refined coordination with dress shirts, leather belts, and loafers.", features: "Tailored Ankle-Length Trousers | Concealed Front Fly Closure | Smooth Woven Texture | Functional Side Slant Pockets | Modern Cropped Hemline | Sturdy Belt Loop Waistband | Smart-Casual and Business Styling Compatibility"}
];



//men outerwear
menOutPath = "../../img/men-outerwear/";
menOutIDHead = "men-out-";
menOutExtn = ".webp"
const menOuterwear = [
	{name: "Brown Utility Field Jacket", image: `${menOutPath}${menOutIDHead}1${menOutExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "139.99", description: "These adult apparel outerwear pieces are constructed with a relaxed silhouette and engineered from a durable woven cotton blend fabric that optimizes breathability during outdoor recreational activities. The design features a classic fold-down collar paired with a full-length button-down front closure to ensure a reliable and customizable fit during active movement. Practical storage is provided by dual flap chest pockets with button closures, while adjustable hem drawstring ties offer a minimal visual accent and tailored drape. Ideal for casual neighborhood walks, outdoor urban exploration, or layered seasonal outings, this jacket provides objective utility and easy coordination with casual t-shirts and denim.", features: "Button-Front Jacket | Turn-Down Collar | Dual Buttoned Chest Pockets | Durable Woven Texture | Hem Drawstring Ties | Adjustable Button Cuffs | T-Shirt and Denim Styling Compatibility"},
	{name: "Lightweight Stand-Collar Utility Vest", image: `${menOutPath}${menOutIDHead}2${menOutExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "109.99", description: "These adult apparel outerwear pieces are constructed with a relaxed sleeveless silhouette and engineered from a smooth lightweight nylon blend fabric that optimizes wind resistance during recreational activities. The design features a protective stand collar paired with a full-length contrast zipper closure to ensure a reliable and temperature-regulating fit during active movement. Practical storage is provided by spacious side slit pockets, while an adjustable elastic hem toggle offers a functional utility accent and customizable waist fit. Ideal for casual neighborhood walks, transition-weather layering, or active weekend outings, this vest provides objective utility and easy coordination with oversized t-shirts.", features: "Sleeveless Zip Vest | High Stand Collar | Smooth Lightweight Shell | Full-Length Front Zipper | Adjustable Toggle Hem | Functional Side Pockets | Layered T-Shirt Styling Compatibility"},
	{name: "Plaid Zip Utility Vest", image: `${menOutPath}${menOutIDHead}3${menOutExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "119.99", description: "These adult apparel outerwear pieces are constructed with a boxy sleeveless silhouette and engineered from a structured woven plaid fabric that optimizes warmth and durability during outdoor activities. The design features a high stand collar paired with a smooth dual-zipper front closure to ensure a secure and adaptable fit during movement. Practical storage is provided by dual expanded cargo-style front pockets with top access, while contrast collar lining and trim offer a subtle graphic visual accent. Ideal for casual outdoor gatherings, urban streetwear layering, or weekend outings, this patterned vest provides objective utility and easy coordination with basic tees and cargo shorts.", features: "Plaid Utility Vest | Stand Collar with Inner Accent | Dual Front Zipper | Structured Woven Texture | Expanded Cargo Pockets | Contrast Bound Edges | Short-Sleeve Styling Compatibility"},
	{name: "Snap-Front Utility Overshirt", image: `${menOutPath}${menOutIDHead}4${menOutExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "129.99", description: "These adult apparel outerwear pieces are constructed with a relaxed silhouette and engineered from a smooth cotton blend fabric that optimizes durability during recreational activities. The design features a classic fold-down collar paired with a full-length metal snap-button front closure to ensure a reliable and customizable fit during active movement. Practical storage is provided by a structured flap chest pocket featuring a subtle woven logo tab, while drop-shoulder long sleeves offer an unrestrictive, easygoing drape. Ideal for casual neighborhood walks, transition-weather layering, or weekend outings, this light jacket provides objective utility and easy coordination with graphic t-shirts.", features: "Snap-Button Front | Point Collar | Flap Chest Pocket | Smooth Cotton Blend | Drop-Shoulder Long Sleeves | Straight Bottom Hem | Layered T-Shirt Styling Compatibility"},
	{name: "Light Wash Denim Overshirt", image: `${menOutPath}${menOutIDHead}5${menOutExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "139.99", description: "These adult apparel outerwear pieces are constructed with a relaxed silhouette and engineered from a lightweight cotton denim fabric that optimizes comfort and breathability during daily wear. The design features a traditional turn-down collar paired with a classic dark button-front closure to ensure a reliable and customizable fit during casual movement. Practical storage is provided by dual buttoned chest flap pockets, while an vintage-inspired light ice-blue wash offers a timeless visual accent. Ideal for casual neighborhood walks, weekend gatherings, or easy everyday layering, this denim shirt provides objective utility and easy coordination with white t-shirts and light-wash trousers.", features: "Light Wash Denim | Turn-Down Collar | Dual Flap Chest Pockets | Button-Front Closure | Button-Cuffed Sleeves | Curved Hemline | Monochromatic Styling Compatibility"},
	{name: "Black Loose Long-Sleeve Overshirt", image: `${menOutPath}${menOutIDHead}6${menOutExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "119.99", description: "These adult apparel outerwear pieces are constructed with a roomy oversized silhouette and engineered from a lightweight woven fabric that optimizes comfort during recreational activities. The design features a neat point collar paired with a contrast white button-front closure to ensure a secure and adaptable fit during active movement. Practical storage is provided by a oversized patch chest pocket featuring tone-on-tone embroidered logo detailing, offering a minimalist visual accent. Ideal for casual outdoor gatherings, evening urban exploration, or relaxed layering, this black overshirt provides objective utility and easy coordination with graphic tees and denim jeans.", features: "Loose Oversized Fit | Point Collar | Contrast Button Closure | Patch Chest Pocket | Tonal Embroidered Branding | Adjustable Cuffs | Graphic Tee Styling Compatibility"},
	{name: "Short-Sleeve Utility Overshirt", image: `${menOutPath}${menOutIDHead}7${menOutExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "99.99", description: "These adult apparel outerwear pieces are constructed with a boxy relaxed silhouette and engineered from a smooth cotton blend fabric that optimizes breathability during warm-weather recreational activities. The design features a traditional point collar paired with a full-length dark button closure to ensure a reliable and adaptable fit during active movement. Practical storage is provided by dual oversized chest utility pockets integrated into horizontal front yoke seams, offering a functional visual accent. Ideal for casual neighborhood walks, summer travel layering, or relaxed weekend outings, this short-sleeve overshirt provides objective utility and easy coordination with basic t-shirts and matching utility shorts.", features: "Short-Sleeve Overshirt | Traditional Point Collar | Button-Down Closure | Dual Oversized Chest Pockets | Smooth Woven Fabric | Boxy Drop-Shoulder Fit | Matching Bottoms Styling Compatibility"},
	{name: "Contrast-Lined Snap Wind Jacket", image: `${menOutPath}${menOutIDHead}8${menOutExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "149.99", description: "These adult apparel outerwear pieces are constructed with a relaxed athletic silhouette and engineered from a lightweight nylon blend fabric that optimizes wind resistance and durability during outdoor activities. The design features a protective high stand collar lined with a vibrant contrast blue interior, paired with a hidden front zipper and snap-button placket to ensure a secure and element-shielding fit during movement. Practical storage is provided by dual patch front pockets and a vertical zipped chest pocket, while contrast stitching throughout offers a modern technical visual accent. Ideal for casual outdoor exploration, evening urban commuting, or transition-weather layering, this jacket provides objective utility and easy coordination with plain white tees and cargo trousers.", features: "Stand-Collar Wind Jacket | Contrast Blue Collar Lining | Hidden Zip & Snap Placket | Contrast Topstitching Detail | Zippered Chest & Dual Patch Pockets | Elasticated Cuffs | Cargo Bottoms Styling Compatibility"}
];



//women top
womenTopPath = "../../img/women-top/";
womenTopIDHead = "women-top-";
womenTopExtn = ".webp"
const womenTop = [
	{name: "Breton Striped Cap-Sleeve Knit Top", image: `${womenTopPath}${womenTopIDHead}1${womenTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "69.99", description: "These adult apparel tops are constructed with a relaxed silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during daily casual wear. The design features a durable ribbed crew neckline paired with soft cap sleeves to ensure a comfortable fit and light shoulder coverage during active movement. Classic visual interest is provided by horizontal nautical-inspired white stripes running across a deep navy base, trimmed with a ribbed hem. Ideal for casual social gatherings, weekend brunch, or summer coastal walks, this striped top provides objective style and easy coordination with denim jeans or casual skirts.", features: "Cap-Sleeve Top | Ribbed Crew Neckline | Horizontal Nautical Stripes | Smooth Knit Texture | Fitted Ribbed Hem | Relaxed Drape | Denim Jeans Styling Compatibility"},
	{name: "Cinch-Hem Short-Sleeve Blouse", image: `${womenTopPath}${womenTopIDHead}2${womenTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "79.99", description: "These adult apparel tops are constructed with a relaxed blouson silhouette and engineered from a lightweight woven cotton blend fabric that optimizes airflow during warm-weather wear. The design features a simple round neckline paired with cap sleeves to ensure an easygoing and unrestrictive fit throughout daily movement. Modern structural detail is provided by an elasticized gathered hemline and a horizontal seam across the lower torso, creating a clean tucked-in visual effect. Ideal for casual office settings, daily errands, or smart-casual weekend outings, this top provides objective utility and easy coordination with wide-leg trousers or pleated skirts.", features: "Short-Sleeve Blouse | Simple Round Neckline | Elasticized Cinch Hem | Lightweight Woven Texture | Horizontal Seam Detail | Cap Sleeves | Wide-Leg Bottoms Styling Compatibility"},
	{name: "Contrast-Trim Knit Crop Tank", image: `${womenTopPath}${womenTopIDHead}3${womenTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "59.99", description: "These adult apparel tops are constructed with a cropped fitted silhouette and engineered from a textured knit cotton blend fabric that optimizes breathability during recreational activities. The design features a flattering scoop neckline paired with sleeveless armholes to ensure a reliable and unrestricted fit during warm-weather movement. Minimalist visual appeal is provided by contrast white stripe tipping along the neckline and armholes, offering a subtle sporty accent. Ideal for casual neighborhood walks, sunny outdoor outings, or relaxed weekend lounging, this cropped top provides objective utility and easy coordination with high-waisted shorts or casual trousers.", features: "Cropped Tank Top | Scoop Neckline | Contrast Stripe Trim | Textured Knit Fabric | Sleeveless Cut | Ribbed Bottom Hem | High-Waisted Bottoms Styling Compatibility"},
	{name: "Beige Color-Block Sleeveless Top", image: `${womenTopPath}${womenTopIDHead}4${womenTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "59.99", description: "These adult apparel tops are constructed with a cropped boxy silhouette and engineered from a lightweight woven cotton blend fabric that optimizes airflow during warm-weather wear. The design features a high crew neckline paired with clean sleeveless armholes to ensure an unrestrictive and structured fit. Modern visual accenting is provided by a bold diagonal tan color-block insert across the lower front bodice, offering an architectural visual element. Ideal for casual outdoor outings, summer travel, or relaxed weekend gatherings, this sleeveless top provides objective utility and easy coordination with high-waisted shorts or white trousers.", features: "Sleeveless Tank Top | High Crew Neckline | Diagonal Color-Block Insert | Lightweight Woven Texture | Cropped Boxy Cut | Straight Bottom Hem | High-Waisted Bottoms Styling Compatibility"},
	{name: "Open-Collar Puff-Sleeve Blouse", image: `${womenTopPath}${womenTopIDHead}5${womenTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "89.99", description: "These adult apparel tops are constructed with a spacious relaxed silhouette and engineered from a lightweight woven linen-cotton blend fabric that optimizes breathability during recreational activities. The design features an open v-neckline with a spread collar paired with voluminous elbow-length puff sleeves to ensure a breezy, comfortable fit. Gathered elastic cuffs and drop shoulders offer a soft, romantic structural accent to the earthy taupe tone. Ideal for casual cafe visits, weekend social gatherings, or relaxed resort wear, this popover blouse provides objective utility and easy coordination with wide-leg trousers or casual shorts.", features: "Popover V-Neckline | Spread Open Collar | Elbow-Length Puff Sleeves | Elasticated Sleeve Cuffs | Drop-Shoulder Fit | Smooth Woven Fabric | Wide-Leg Bottoms Styling Compatibility"},
	{name: "Soft Pink Gathered Blouse", image: `${womenTopPath}${womenTopIDHead}6${womenTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "69.99", description: "These adult apparel tops are constructed with a relaxed silhouette and engineered from a smooth woven cotton blend fabric that optimizes breathability during daily casual wear. The design features a neat crew neckline paired with subtly gathered short cap sleeves to ensure a comfortable fit and effortless movement. Subtle visual detail is provided by a clean vertical center seam running down the front torso, offering a refined geometric accent. Ideal for casual neighborhood walks, weekend gatherings, or relaxed office environments, this pastel top provides objective utility and easy coordination with denim jeans or casual skirts.", features: "Short-Sleeve Blouse | Simple Crew Neckline | Gathered Shoulder Detail | Vertical Center Seam | Smooth Woven Fabric | Relaxed Drape | Denim Styling Compatibility"},
	{name: "Fine-Striped Ringer Crewneck Tee", image: `${womenTopPath}${womenTopIDHead}7${womenTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "59.99", description: "These adult apparel tops are constructed with a classic relaxed silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during recreational activities. The design features a supportive contrast navy ribbed crew neckline paired with set-in short sleeves to ensure a reliable and flexible fit during casual movement. Visual detail is provided by fine horizontal micro-stripes running across the body, complemented by subtle embroidered text branding on the left chest. Ideal for casual neighborhood walks, indoor gym sessions, or relaxed weekend lounging, this short-sleeve tee provides objective utility and easy coordination with linen shorts or casual trousers.", features: "Short-Sleeve T-Shirt | Contrast Ringer Crewneck | Micro-Striped Pattern | Chest Embroidered Detail | Smooth Knit Texture | Straight Bottom Hem | Casual Shorts Styling Compatibility"},
	{name: "Utility Flap Pocket Cap-Sleeve Tee", image: `${womenTopPath}${womenTopIDHead}8${womenTopExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "69.99", description: "These adult apparel tops are constructed with a spacious boxy silhouette and engineered from a smooth knit cotton blend fabric that optimizes breathability during warm-weather wear. The design features a flexible crew collar paired with angled cap-style sleeves to ensure an easygoing, unrestrictive fit throughout daily activities. Practical storage is provided by dual contrast cargo-style flap pockets with snap closures placed near the hem, offering a modern functional visual accent. Ideal for casual neighborhood walks, daily errands, or outdoor weekend activities, this top provides objective utility and easy coordination with dark trousers or relaxed shorts.", features: "Cap-Sleeve Tee | Crew Neckline | Dual Flap Cargo Pockets | Snap-Button Pocket Closures | Smooth Knit Texture | Boxy Relaxed Cut | Trousers Styling Compatibility"}
];



//women bottom
womenBotPath = "../../img/women-bottom/";
womenBotIDHead = "women-bot-";
womenBotExtn = ".webp"
const womenBottom = [
	{name: "Charcoal Snap-Side Wide Trousers", image: `${womenBotPath}${womenBotIDHead}1${womenBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "119.99", description: "These adult apparel bottoms are constructed with a wide-leg silhouette and engineered from a smooth lightweight nylon blend fabric that optimizes breathability during recreational activities. The design features a supportive elastic waistband to ensure a reliable and customized fit during active movement. Practical storage is provided by discreet side pockets, while decorative tone-on-tone snap buttons running down the side seams offer a modern utility visual accent. Ideal for casual neighborhood walks, outdoor urban exploration, or relaxed weekend lounging, these trousers provide objective utility and easy coordination with sleeveless vests or casual t-shirts.", features: "Wide-Leg Trousers | Elastic Waistband | Side Snap Button Details | Smooth Lightweight Fabric | Functional Side Pockets | Full-Length Cut | Vest Styling Compatibility"},
	{name: "Pleated Wide-Leg Cropped Culottes", image: `${womenBotPath}${womenBotIDHead}2${womenBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "99.99", description: "These adult apparel bottoms are constructed with an ultra-wide flared silhouette and engineered from a smooth woven cotton blend fabric that optimizes airflow during warm-weather wear. The design features a supportive elasticized waistband paired with subtle front waist pleats to ensure a reliable fit and fluid drape during movement. Practical storage is provided by functional side seam pockets, while the relaxed mid-calf length offers a minimal visual accent. Ideal for casual neighborhood walks, daily errands, or relaxed weekend lounging, these culottes provide objective utility and easy coordination with polo tops or knit sweaters.", features: "Wide-Leg Culottes | Elastic Waistband | Front Pleat Details | Cropped Mid-Calf Length | Functional Side Pockets | Flowy Woven Texture | Polo Styling Compatibility"},
	{name: "Relaxed Fit High-Waist Denim Shorts", image: `${womenBotPath}${womenBotIDHead}3${womenBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "79.99", description: "These adult apparel bottoms are constructed with an A-line relaxed silhouette and engineered from a durable cotton denim fabric that optimizes breathability during recreational activities. The design features a structured high-rise waistband with belt loops paired with a classic zip fly closure to ensure a secure and flattering fit. Practical storage is provided by traditional front and back pockets, while heavy contrast topstitching along the hems offers a classic casual visual accent. Ideal for sunny outdoor outings, summer travel, or relaxed weekend activities, these denim shorts provide objective utility and easy coordination with striped t-shirts or casual tops.", features: "High-Waist Denim Shorts | Zip Fly & Button Closure | Classic Five-Pocket Layout | Durable Cotton Denim | Topstitched Bottom Hem | Relaxed A-Line Cut | Graphic Tee Styling Compatibility"},
	{name: "Elastic Waist Balloon Trousers", image: `${womenBotPath}${womenBotIDHead}4${womenBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "109.99", description: "These adult apparel bottoms are constructed with a voluminous balloon silhouette and engineered from a smooth woven cotton blend fabric that optimizes breathability during recreational activities. The design features a supportive elastic waistband paired with subtle waist gathering to ensure a reliable and customized fit during active movement. Practical storage is provided by discreet side pockets, while the tapered ankle-length hem offers a minimal visual accent. Ideal for casual neighborhood walks, indoor gym sessions, or relaxed weekend lounging, these trousers provide objective utility and easy coordination with sleeveless tops.", features: "Balloon Trousers | Elastic Waistband | Gathered Waist Detail | Smooth Woven Fabric | Functional Side Pockets | Tapered Ankle Hem | Sleeveless Styling Compatibility"},
	{name: "Vertical Striped Button-Detail Shorts", image: `${womenBotPath}${womenBotIDHead}5${womenBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "79.99", description: "These adult apparel bottoms are constructed with a relaxed silhouette and engineered from a lightweight woven cotton blend fabric that optimizes airflow during warm-weather wear. The design features a supportive elasticized waistband paired with decorative front button closures to ensure a reliable fit and easy wearability. Practical storage is provided by discreet side seam pockets, while subtle vertical pinstriping running down the body offers a minimal visual accent. Ideal for casual neighborhood walks, outdoor summer activities, or relaxed weekend lounging, these shorts provide objective utility and easy coordination with casual t-shirts.", features: "Casual Shorts | Elastic Waistband | Front Decorative Buttons | Vertical Pinstripe Pattern | Functional Side Pockets | Straight Bottom Hem | Oversized Tee Styling Compatibility"},
	{name: "High-Waist Longline Denim Shorts", image: `${womenBotPath}${womenBotIDHead}6${womenBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "89.99", description: "These adult apparel bottoms are constructed with a relaxed mid-thigh silhouette and engineered from a durable cotton denim fabric that optimizes breathability during recreational activities. The design features a supportive high-rise waistband paired with a classic zip fly and button closure to ensure a reliable and comfortable fit. Practical storage is provided by a functional five-pocket layout, while a faded light wash finish offers a subtle casual visual accent. Ideal for casual neighborhood walks, outdoor weekend outings, or relaxed summer lounging, these knee-length shorts provide objective utility and easy coordination with tank tops.", features: "Longline Denim Shorts | High-Rise Fit | Zip Fly and Button Closure | Classic Five Pockets | Light Wash Denim | Clean Stitched Hem | Tank Top Styling Compatibility"},
	{name: "Wide-Leg Cropped Utility Culottes", image: `${womenBotPath}${womenBotIDHead}7${womenBotExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "99.99", description: "These adult apparel bottoms are constructed with a wide-leg flared silhouette and engineered from a smooth woven cotton blend fabric that optimizes breathability during recreational activities. The design features a supportive flat-front waistband with an elasticized back to ensure a reliable and customized fit during active movement. Practical storage is provided by discreet side seam pockets, while the breezy cropped mid-calf length offers a minimal visual accent. Ideal for casual neighborhood walks, indoor gym sessions, or relaxed weekend lounging, these culottes provide objective utility and easy coordination with knit tops or casual t-shirts.", features: "Wide-Leg Culottes | Elasticized Waistband | Smooth Woven Texture | Cropped Mid-Calf Length | Functional Side Pockets | Clean Straight Hem | Short-Sleeve Knit Styling Compatibility"}
];



//women dress
womenDrsPath = "../../img/women-dress/";
womenDrsIDHead = "women-drs-";
womenDrsExtn = ".webp"
const womenDress = [
	{name: "Half-Zip Drawstring Waist Dress", image: `${womenDrsPath}${womenDrsIDHead}1${womenDrsExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "129.99", description: "These adult apparel dresses are constructed with an A-line relaxed silhouette and engineered from a smooth woven cotton blend fabric that optimizes breathability during recreational activities. The design features a smart open collar paired with a half-zipper neckline and short sleeves to ensure a customizable and comfortable fit during movement. An adjustable toggle drawstring waist offers a minimal visual accent while defining the silhouette. Ideal for casual neighborhood walks, outdoor afternoon outings, or relaxed weekend gatherings, this knee-length dress provides objective utility and easy coordination with sneakers or sandals.", features: "Knee-Length Dress | Half-Zip Neckline | Open Collar | Drawstring Toggle Waist | Smooth Woven Texture | Short Sleeves | Casual Footwear Styling Compatibility"},
	{name: "Sleeveless Hem Midi Dress", image: `${womenDrsPath}${womenDrsIDHead}2${womenDrsExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "139.99", description: "These adult apparel dresses are constructed with a flowy relaxed silhouette and engineered from a smooth lightweight woven fabric that optimizes drape and airflow during warm-weather wear. The design features a modest high crew neckline paired with clean sleeveless armholes to ensure an unrestrictive and graceful fit throughout daily movement. Practical storage is provided by discreet side seam pockets, while a subtle asymmetric curved hemline offers a modern architectural visual accent. Ideal for casual neighborhood walks, museum visits, or relaxed evening dinners, this midi dress provides objective utility and easy coordination with slides or loafers.", features: "Sleeveless Midi Dress | High Crew Neckline | Asymmetric Curved Hem | Smooth Woven Fabric | Functional Side Pockets | Loose A-Line Cut | Slide Sandals Styling Compatibility"},
	{name: "Gathered Cap-Sleeve Midi Dress", image: `${womenDrsPath}${womenDrsIDHead}3${womenDrsExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "139.99", description: "These adult apparel dresses are constructed with an elongated relaxed silhouette and engineered from a lightweight woven cotton blend fabric that optimizes breathability during warm-weather wear. The design features a classic crew neckline paired with soft cap sleeves to ensure an easygoing and comfortable fit. Visual focus is provided by dense elasticized waist cinching across the midsection, creating a flattering flared skirt and subtle gathered accents. Ideal for casual neighborhood walks, weekend brunch, or summer travel, this vibrant midi dress provides objective utility and easy coordination with casual sneakers or flats.", features: "Cap-Sleeve Midi Dress | Classic Crew Neckline | Elasticized Gathered Waist | Lightweight Woven Texture | Flared Ankle-Length Skirt | Vibrant Solid Finish | Casual Sneakers Styling Compatibility"},
	{name: "Floral Print Sleeveless Shift Dress", image: `${womenDrsPath}${womenDrsIDHead}4${womenDrsExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "119.99", description: "These adult apparel dresses are constructed with an A-line relaxed silhouette and engineered from a smooth woven cotton blend fabric that optimizes breathability during warm-weather recreational activities. The design features a classic round neckline paired with sleeveless armholes to ensure a reliable and unrestricted fit during movement. Bold visual focus is provided by an all-over oversized floral print in deep navy against a light off-white background, offering a vibrant summer aesthetic. Ideal for casual neighborhood walks, weekend garden gatherings, or relaxed resort wear, this mini dress provides objective utility and easy coordination with casual sandals or slides.", features: "Sleeveless Shift Dress | Round Neckline | Oversized Floral Print | Smooth Woven Fabric | Relaxed A-Line Silhouette | Above-the-Knee Hem | Casual Sandals Styling Compatibility"},
	{name: "Short-Sleeve Tiered Utility Dress", image: `${womenDrsPath}${womenDrsIDHead}5${womenDrsExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "139.99", description: "These adult apparel dresses are constructed with a flared midi silhouette and engineered from a lightweight woven cotton blend fabric that optimizes airflow during daily wear. The design features a traditional point collar paired with a full-length button-down front closure and short sleeves to ensure a versatile, customizable fit. Subtle structural detail is provided by a waist seam with gentle gathering and flat chest patch seams, adding a modern utility visual accent. Ideal for casual neighborhood walks, weekend social gatherings, or light outdoor travel, this olive midi dress provides objective utility and easy coordination with sneakers or loafers.", features: "Midi Shirt Dress | Turn-Down Point Collar | Full-Length Button Placket | Gathered Waist Seam | Short Sleeves | Lightweight Woven Texture | Sneakers Styling Compatibility"},
	{name: "Beige Half-Zip Toggle Waist Dress", image: `${womenDrsPath}${womenDrsIDHead}6${womenDrsExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "129.99", description: "These adult apparel dresses are constructed with an A-line relaxed silhouette and engineered from a smooth woven cotton blend fabric that optimizes breathability during recreational activities. The design features an open point collar paired with a half-zipper front closure and roomy short sleeves to ensure a flexible and customizable fit during active movement. Practical adjustment is enabled by an internal drawstring waist with a toggle closure, offering a functional visual accent and personalized waist definition. Ideal for casual neighborhood walks, daily errands, or relaxed weekend outings, this knee-length dress provides objective utility and easy coordination with casual sneakers or slip-ons.", features: "Knee-Length Dress | Half-Zip Neckline | Open Point Collar | Drawstring Waist with Toggle | Short Sleeves | Smooth Woven Texture | Casual Footwear Styling Compatibility"},
	{name: "Split-Neck Cap-Sleeve Midi Dress", image: `${womenDrsPath}${womenDrsIDHead}7${womenDrsExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "139.99", description: "These adult apparel dresses are constructed with an elongated relaxed silhouette and engineered from a smooth lightweight woven cotton blend fabric that optimizes breathability during warm-weather recreational activities. The design features a notch v-neckline with a half button placket paired with cap sleeves to ensure a comfortable and unrestrictive fit. Elasticized smocking along the waistline provides a defined fit and gentle gathered visual accent. Ideal for casual neighborhood walks, weekend brunch, or relaxed summer travel, this light grey midi dress provides objective utility and easy coordination with sneakers or casual flats.", features: "Cap-Sleeve Midi Dress | Split Notch V-Neckline | Half Button Placket | Elasticized Smocked Waist | Smooth Woven Texture | Flared Midi Skirt | Casual Footwear Styling Compatibility"},
	{name: "Dark Denim Sleeveless Shift Dress", image: `${womenDrsPath}${womenDrsIDHead}8${womenDrsExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "129.99", description: "These adult apparel dresses are constructed with an A-line relaxed silhouette and engineered from a structured dark wash cotton denim fabric that optimizes durability during recreational activities. The design features a modest round crew neckline paired with sleeveless armholes to ensure a flexible and unrestricted fit during active movement. Practical storage is provided by a chest patch pocket outlined in contrast topstitching, while a gingham check fabric trim along the bottom hem offers a subtle play on layers. Ideal for casual neighborhood walks, weekend outings, or relaxed daily wear, this denim shift dress provides objective utility and easy coordination with casual sneakers.", features: "Sleeveless Shift Dress | Round Crew Neckline | Dark Indigo Denim | Contrast Topstitched Pocket | Gingham Trim Bottom Hem | Relaxed A-Line Cut | Casual Sneakers Styling Compatibility"}
];



//women skirt
womenSktPath = "../../img/women-skirt/";
womenSktIDHead = "women-skt-";
womenSktExtn = ".webp"
const womenSkirt = [
	{name: "Pleated Flared Midi Skirt", image: `${womenSktPath}${womenSktIDHead}1${womenSktExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "99.99", description: "These adult apparel skirts are constructed with a flared A-line silhouette and engineered from a smooth woven cotton blend fabric that optimizes breathability during recreational activities. The design features a fitted waist with subtle front gathering and a matching belt loop detail to ensure a customized and reliable fit during active movement. Flattering vertical box pleats cascading down the skirt provide an elegant fluid drape and minimal visual accent. Ideal for casual neighborhood walks, sunny weekend brunches, or relaxed summer outings, this bright midi skirt provides objective utility and easy coordination with linen blouses or casual t-shirts.", features: "Flared Midi Skirt | Fitted Waistband | Box Pleat Details | Smooth Woven Texture | Flowy A-Line Cut | Below-the-Knee Hem | Button-Up Blouse Styling Compatibility"},
	{name: "Elastic Waist Utility Mini Skirt", image: `${womenSktPath}${womenSktIDHead}2${womenSktExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "79.99", description: "These adult apparel skirts are constructed with a structured A-line silhouette and engineered from a durable woven cotton blend fabric that optimizes air circulation during warm-weather wear. The design features a comfortable elastic waistband paired with a faux fly front to ensure an unrestrictive, easy-pull-on fit. Practical storage is provided by spacious side patch pockets, while double-stitched hem seams offer a functional utility visual accent. Ideal for casual neighborhood walks, outdoor afternoon activities, or relaxed summer lounging, this khaki mini skirt provides objective utility and easy coordination with tank tops or basic tees.", features: "Utility Mini Skirt | Elastic Waistband | Side Patch Pockets | Faux Fly Front | Durable Woven Texture | Above-the-Knee Cut | Tank Top Styling Compatibility"},
	{name: "Watercolor Tiered Ruffle Midi Skirt", image: `${womenSktPath}${womenSktIDHead}3${womenSktExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "109.99", description: "These adult apparel skirts are constructed with a flowy tiered silhouette and engineered from a lightweight woven fabric that optimizes graceful drape during recreational activities. The design features a supportive elasticized waistband to ensure a flexible and customized fit throughout daily movement. Visual elegance is provided by an all-over soft watercolor abstract print in pastel pink and green hues, finished with a subtle ruffled tier seam near the lower hem. Ideal for casual neighborhood walks, weekend garden gatherings, or relaxed resort wear, this printed skirt provides objective utility and easy coordination with sleeveless knit tops.", features: "Tiered Midi Skirt | Elasticized Waistband | Ruffled Seam Detail | Abstract Watercolor Print | Flowy Lightweight Texture | Mid-Calf Length | Sleeveless Knit Styling Compatibility"},
	{name: "Fine-Striped Drawstring Midi Skirt", image: `${womenSktPath}${womenSktIDHead}4${womenSktExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "89.99", description: "These adult apparel skirts are constructed with a flared A-line silhouette and engineered from a smooth woven cotton blend fabric that optimizes breathability during recreational activities. The design features a supportive elastic waistband paired with an adjustable external drawstring to ensure a reliable and customized fit during active movement. Fine vertical pinstriping running throughout the fabric provides a crisp nautical visual accent, complemented by functional side pockets for practical storage. Ideal for casual neighborhood walks, indoor gym sessions, or relaxed weekend lounging, this midi skirt provides objective utility and easy coordination with casual t-shirts.", features: "Flared Midi Skirt | Elastic Waistband | Adjustable Drawstring | Fine Vertical Pinstripes | Smooth Woven Texture | Functional Side Pockets | T-Shirt Styling Compatibility"},
	{name: "Dust Blue Cargo Pocket Midi Skirt", image: `${womenSktPath}${womenSktIDHead}5${womenSktExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "109.99", description: "These adult apparel skirts are constructed with a structured straight silhouette and engineered from a smooth lightweight nylon blend fabric that optimizes wind resistance during outdoor activities. The design features a flat-front elastic waistband to ensure a secure fit and comfortable drape throughout daily movement. Practical storage is provided by side flap cargo pockets, while a cinchable drawstring gather along the lower side hem offers a modern technical visual accent. Ideal for casual neighborhood walks, outdoor urban exploration, or relaxed weekend outings, this utility skirt provides objective utility and easy coordination with sleeveless jackets or casual tops.", features: "Utility Midi Skirt | Flat Elastic Waistband | Flap Cargo Side Pockets | Drawstring Cinch Hem Detail | Smooth Lightweight Fabric | Straight Cut Silhouette | Vest Styling Compatibility"},
	{name: "Light Blue Eyelet Floral Midi Skirt", image: `${womenSktPath}${womenSktIDHead}6${womenSktExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "119.99", description: "These adult apparel skirts are constructed with a full flared silhouette and engineered from a lightweight woven cotton blend fabric that optimizes airflow and delicate drape during warm-weather wear. The design features an elasticized gathered waistband to ensure a flexible and comfortable fit throughout daily activities. Visual elegance is provided by intricate floral eyelet embroidery running across the light pastel blue fabric, adding an airy tactile visual accent. Ideal for casual neighborhood walks, weekend garden gatherings, or relaxed summer travel, this embroidered skirt provides objective utility and easy coordination with sleeveless utility tops or blouses.", features: "Flared Midi Skirt | Elasticized Waistband | Intricate Eyelet Embroidery | Floral Cutout Pattern | Lightweight Woven Texture | Full Volume A-Line Drape | Utility Vest Styling Compatibility"},
	{name: "Soft Pink Flared Midi Skirt", image: `${womenSktPath}${womenSktIDHead}7${womenSktExtn}`, bonusImages: [``, ``, ``, ``, ``], price: "89.99", description: "These adult apparel skirts are constructed with a flared relaxed silhouette and engineered from a lightweight woven cotton blend fabric that optimizes breathability during warm-weather recreational activities. The design features a supportive elasticized waistband paired with subtle waist gathering to ensure a reliable and comfortable fit during active movement. Practical storage is provided by discreet side seam pockets, while the flowy mid-calf length offers a graceful and minimal visual accent. Ideal for casual neighborhood walks, weekend garden gatherings, or relaxed summer lounging, this pastel midi skirt provides objective utility and easy coordination with short-sleeve polo tops or casual knitwear.", features: "Flared Midi Skirt | Elasticized Gathered Waist | Lightweight Woven Texture | Functional Side Pockets | Flowy A-Line Cut | Pastel Pink Finish | Polo Top Styling Compatibility"}
];



const productCategories = [
	menTop,
	menBottom,
	menOuterwear,
	womenTop,
	womenBottom,
	womenDress,
	womenSkirt
];
